Repository 202212-GIZ-YE-FEW/Tabadul, pull requests merged in 2023-05, with the labels that each got.

#123 keep selected language in all pages
  src/components/Navbar/NavItem.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/__test__/Navbar.test.js
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/pages/_app.jsx
  src/pages/_document.jsx
Labels: fix, Language

#127 category enhancement
  src/components/CardListed/__test__/__snapshots__/CardListed.test.js.snap
  src/components/Categories/Categories.styled.jsx
  src/components/Categories/__test__/__snapshots__/Categories.test.js.snap
Labels: enhancement, fix

#129 loading desgin
  src/components/Loading/__test__/Loading.test.js
  src/components/Loading/__test__/__snapshots__/Loading.test.js.snap
  src/components/Loading/index.jsx
  src/components/Loading/loading.styled.jsx
  src/pages/_app.jsx
Labels: Component finished

#134 add information to a single product page
  src/components/AddItem/Index.jsx
  src/components/ProductPgage/ProductPage.jsx
  src/components/ProductPgage/__test__/__snapshots__/ProductPgage.test.js.snap
  src/components/Sign UP/Index.jsx
  src/components/Signin/Signin.styled.jsx
  src/components/Signin/__test__/__snapshots__/Signin.test.js.snap
  src/pages/Products/[pid].jsx
Labels: bug, firebase, feature

#136 login page responsiveness bug
  src/components/Signin/Signin.styled.jsx
  src/components/Signin/__test__/__snapshots__/Signin.test.js.snap
  src/components/Signin/index.jsx
Labels: bug, fix

#142 center everything to the middle like figma design & links
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.style.jsx
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
Labels: enhancement, style

#145 Make Profile Dynamic with firebase
  src/components/Navbar/Navbar.jsx
  src/components/Profile/MyItems/MyItems.styled.jsx
  src/components/Profile/MyItems/__test__/__snapshots__/MyItems.test.js.snap
  src/components/Profile/MyItems/index.jsx
  src/components/Profile/UserDetails/UserDetails.style.jsx
  src/components/Profile/UserDetails/__test__/__snapshots__/UserDetails.test.js.snap
  src/components/Profile/UserDetails/index.jsx
  src/pages/Profile/Index.jsx
  src/pages/Updateproduct/index.jsx
  src/pages/Updateuser/index.jsx
  src/styles/Updateuser.styled.jsx
  src/styles/profile.styled.jsx
Labels: enhancement, Component finished, fix, page completed, firebase

#147 fix category selection
  src/components/AddItem/Index.jsx
Labels: fix

#149 adding animation to the Website
  package-lock.json
  package.json
  src/components/Blogs/SingleBlogCard/__test__/__snapshots__/SingleBlogCard.test.js.snap
  src/components/Blogs/SingleBlogCard/index.jsx
  src/components/Card/Card.jsx
  src/components/Card/__test__/__snapshots__/Card.test.js.snap
  src/components/Causes/__test__/__snapshots__/Causes.test.js.snap
  src/components/Causes/index.jsx
  src/components/Herro/IntroductionImage.jsx
  src/components/Herro/__test__/__snapshots__/Hero.test.js.snap
  src/components/Herro/index.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/SingleBlog/__test__/__snapshots__/SingleBlog.test.js.snap
  src/components/SingleBlog/index.jsx
  src/components/TeamMember/__test__/__snapshots__/TeamMember.test.js.snap
  src/components/TeamMember/index.jsx
  src/pages/Aboutus/index.jsx
  src/pages/_app.jsx
Labels: enhancement

#152 fix singleProduct
  src/pages/Products/[pid].jsx
Labels: fix

#154 Rename Index.jsx to index.jsx
  src/pages/Products/index.jsx
Labels: fix

#151 improvements
  data/db.js
  src/assets/Image/Ahmed.jpg
  src/assets/Image/FB_IMG_1660682652060.jpg
  src/assets/Image/amazon.png
  src/assets/Image/aseel.jpg
  src/assets/Image/pebble.png
  src/assets/Image/recoded.png
  src/assets/Image/sana.jpg
  src/assets/Image/sara.jpg
  src/assets/Image/share1.png
  src/assets/Image/share2.jfif
  src/assets/Image/share2.png
  src/assets/Image/shopify.webp
  src/assets/Image/yassin.jpg
  src/components/AddItem/AddItem.styled.jsx
  src/components/AddItem/__test__/__snapshots__/AddItem.test.js.snap
  src/components/Blogs/SingleBlogCard/SingleBlogCard.styled.jsx
  src/components/Blogs/SingleBlogCard/__test__/__snapshots__/SingleBlogCard.test.js.snap
  src/components/Card/Card.styled.jsx
  src/components/Card/__test__/__snapshots__/Card.test.js.snap
  src/components/CardListed/__test__/__snapshots__/CardListed.test.js.snap
  src/components/Categories/Categories.styled.jsx
  src/components/Categories/__test__/__snapshots__/Categories.test.js.snap
  src/components/Herro/__test__/__snapshots__/Hero.test.js.snap
  src/components/Herro/hero.style.jsx
  src/components/Partners/index.jsx
  src/components/Sign UP/Signup.styled.jsx
  src/components/Sign UP/__test__/__snapshots__/Signup.test.js.snap
  src/components/Signin/Signin.styled.jsx
  src/components/Signin/__test__/__snapshots__/Signin.test.js.snap
  src/components/SingleBlog/SingleBlog.styled.jsx
  src/components/SingleBlog/__test__/__snapshots__/SingleBlog.test.js.snap
  src/components/TeamMember/TeamMember.styled.jsx
  src/components/TeamMember/__test__/__snapshots__/TeamMember.test.js.snap
  src/pages/Forgetpassword/index.jsx
  src/styles/aboutus.styled.jsx
  src/styles/error.styled.jsx
  src/styles/forgetpassword.styled.jsx
Labels: documentation, style

#158 Fix the location selection underlap
  src/components/Card/Card.styled.jsx
  src/components/Card/__test__/__snapshots__/Card.test.js.snap
  src/components/ListedItems/ListedItems.styled.jsx
Labels: fix, style

#162 Fix Profile page
  public/locales/ar/profile.json
  public/locales/en/profile.json
  src/components/AddItem/Index.jsx
  src/components/ProductPgage/product.style.jsx
  src/components/Profile/UserDetails/UserDetails.style.jsx
  src/components/Profile/UserDetails/__test__/UserDetails.test.js
  src/components/Profile/UserDetails/__test__/__snapshots__/UserDetails.test.js.snap
  src/components/Profile/UserDetails/index.jsx
  src/pages/Products/[pid].jsx
  src/pages/Profile/index.jsx
Labels: enhancement, fix, style

#165 fix profile my item
  src/assets/Image/nodata.svg
  src/components/Causes/__test__/__snapshots__/Causes.test.js.snap
  src/components/Causes/index.jsx
  src/components/Herro/__test__/__snapshots__/Hero.test.js.snap
  src/components/Herro/hero.style.jsx
  src/components/Profile/MyItems/MyItems.styled.jsx
  src/components/Profile/MyItems/__test__/__snapshots__/MyItems.test.js.snap
  src/components/Profile/MyItems/index.jsx
  src/pages/index.jsx
  src/styles/globals.css
Labels: bug, fix, firebase

#169 fix DonateNow button
  src/components/Herro/DonateButton.jsx
Labels: fix

#167 authentication with google
  public/images/Google.svg
  src/components/Profile/UserDetails/index.jsx
  src/components/Sign UP/Index.jsx
  src/components/Sign UP/Signup.styled.jsx
  src/components/Sign UP/__test__/__snapshots__/Signup.test.js.snap
  src/components/Signin/Signin.styled.jsx
  src/components/Signin/__test__/__snapshots__/Signin.test.js.snap
  src/components/Signin/index.jsx
  src/pages/index.jsx
Labels: firebase, feature
