Repository 202212-GIZ-YE-FEW/Tabadul, pull requests merged in 2023-04, with the labels that each got.

#35 Create listed-items page
  data/db.js
  src/components/CardListed/__test__/__snapshots__/CardListed.test.js.snap
  src/components/CardListed/index.jsx
  src/components/Categories/Categories.styled.jsx
  src/components/Categories/__test__/__snapshots__/Categories.test.js.snap
  src/components/Categories/index.jsx
  src/components/ListedItems/ButtonsComp.jsx
  src/components/ListedItems/ItemsList.jsx
  src/components/ListedItems/ListedItems.jsx
  src/components/ListedItems/SwapIcons.jsx
  src/components/ListedItems/__test__/__snapshots__/SearchAndList.test.js.snap
  src/pages/addToItem.jsx
  src/pages/index.jsx
  src/pages/listOfItems.jsx
Labels: enhancement, page completed

#37 Sign Up
  public/images/Facebook.svg
  public/images/Instagram.svg
  public/images/Linkedin.svg
  src/components/Sign UP/Index.jsx
  src/components/Sign UP/Signup.styled.jsx
  src/components/Sign UP/__test__/Signup.test.js
  src/components/Sign UP/__test__/__snapshots__/Signup.test.js.snap
Labels: enhancement

#39 feat(created single blog card): created Single blog card component
  package-lock.json
  public/images/donation.svg
  src/components/Blogs/SingleBlogCard/SingleBlogCard.styled.jsx
  src/components/Blogs/SingleBlogCard/__test__/SingleBlogCard.test.js
  src/components/Blogs/SingleBlogCard/__test__/__snapshots__/SingleBlogCard.test.js.snap
  src/components/Blogs/SingleBlogCard/index.jsx
Labels: Component finished

#40 8 create blogs section
  src/components/Blogs/BlogContainer/BlogContainer.styled.jsx
  src/components/Blogs/BlogContainer/__test__/BlogContainer.test.js
  src/components/Blogs/BlogContainer/__test__/__snapshots__/BlogContainer.test.js.snap
  src/components/Blogs/BlogContainer/index.jsx
  src/pages/index.jsx
Labels: Component finished

#42 Blog Component & Page
  data/Blogs.js
  data/db.js
  src/assets/Image/Photo.svg
  src/components/SingleBlog/SingleBlog.styled.jsx
  src/components/SingleBlog/__test__/SingleBlog.test.js
  src/components/SingleBlog/__test__/__snapshots__/SingleBlog.test.js.snap
  src/components/SingleBlog/index.jsx
  src/pages/Blogs/[pid].jsx
  src/pages/Blogs/index.jsx
  src/pages/index.jsx
Labels: Component finished

#48 Add responsive
  src/components/Blogs/BlogContainer/BlogContainer.styled.jsx
  src/components/Blogs/BlogContainer/__test__/__snapshots__/BlogContainer.test.js.snap
  src/components/Blogs/BlogContainer/index.jsx
  src/components/Blogs/SingleBlogCard/SingleBlogCard.styled.jsx
  src/components/Blogs/SingleBlogCard/__test__/__snapshots__/SingleBlogCard.test.js.snap
  src/components/PopularItems/PopularItems.styled.jsx
  src/components/PopularItemsSection/__test__/__snapshots__/PopularItemsSection.test.js.snap
Labels: fix

#45 Add folders for pages
  src/pages/About us/Index.jsx
  src/pages/Add Items/Index.jsx
  src/pages/Products/Index.jsx
  src/pages/Profile/Index.jsx
  src/pages/Sign in/Index.jsx
  src/pages/Sign up/Index.jsx
Labels: documentation

#51 Firebase apis
  next.config.js
  package-lock.json
  package.json
  public/thumbnails/default-image.png
  src/components/AddItem/AddItem.styled.jsx
  src/components/AddItem/Index.jsx
  src/components/AddItem/__test__/__snapshots__/AddItem.test.js.snap
  src/components/Categories/index.jsx
  src/components/ListedItems/ButtonsComp.jsx
  src/components/ListedItems/ItemsList.jsx
  src/components/ListedItems/ListedItems.jsx
  src/components/ListedItems/ListedItems.styled.jsx
  src/components/ListedItems/__test__/__snapshots__/SearchAndList.test.js.snap
  src/pages/addToItem.jsx
  src/pages/listOfItems.jsx
  src/utils/firebase.js
Labels: enhancement, fix, configuration

#53 fix updating products items
  src/components/Categories/index.jsx
  src/pages/listOfItems.jsx
Labels: fix

#54 Single blog
  src/pages/Blogs/[pid].jsx
  src/styles/Blogs.styled.jsx
Labels: enhancement

#58 Refactor: change listOfItems page place
  src/pages/Products/Index.jsx
  src/pages/Products/[pid].jsx
  src/pages/listOfItems.jsx
Labels: enhancement, fix

#66 Enhance products page
  public/images/tag-fill.svg
  src/components/ListedItems/ItemsList.jsx
  src/components/ListedItems/ListedItems.styled.jsx
Labels: style

#65 firebase Configuration with Blog , Single Page & fix dynamic route
  next.config.js
  src/components/SingleBlog/SingleBlog.styled.jsx
  src/components/SingleBlog/__test__/__snapshots__/SingleBlog.test.js.snap
  src/components/SingleBlog/index.jsx
  src/pages/Blogs/[pid].jsx
  src/pages/Blogs/index.jsx
  src/pages/index.jsx
  src/styles/Blogs.styled.jsx
  src/utils/firebase.js
Labels: enhancement, page completed, configuration, dynamic, Week3

#62 Modify files names
  src/pages/About us/Index.jsx
  src/pages/AddItems/index.jsx
  src/pages/Signin/index.jsx
  src/pages/Signup/index.jsx
  src/pages/index.jsx
Labels: documentation

#72 Disappear drop menu when click outside of it
  src/components/ListedItems/ButtonsComp.jsx
  src/components/ListedItems/SearchComp.jsx
  src/components/ListedItems/__test__/__snapshots__/SearchAndList.test.js.snap
Labels: enhancement, fix

#73 Adding ar language to about page & Alignment
  data/db.js
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/TeamMember/TeamMember.styled.jsx
  src/components/TeamMember/__test__/__snapshots__/TeamMember.test.js.snap
  src/pages/Aboutus/index.jsx
  src/pages/index.jsx
Labels: enhancement, Language

#76 Enhance search performance
  src/components/ListedItems/ListedItems.jsx
Labels: enhancement

#80 Design sign in page
  public/images/Signin.svg
  src/components/Signin/Signin.styled.jsx
  src/components/Signin/__test__/Signin.test.js
  src/components/Signin/__test__/__snapshots__/Signin.test.js.snap
  src/components/Signin/index.jsx
  src/pages/Signin/index.jsx
Labels: style, feature

#81 Fix add item uploading images and other
  public/addToItem/delete.svg
  src/components/AddItem/AddItem.styled.jsx
  src/components/AddItem/Index.jsx
  src/components/AddItem/__test__/__snapshots__/AddItem.test.js.snap
  src/components/ListedItems/ItemsList.jsx
Labels: enhancement, firebase, style

#84 Fix products and blogs shown items in homepage
  src/components/Blogs/BlogContainer/index.jsx
  src/components/PopularItems/PopularItems.styled.jsx
  src/components/PopularItems/__test__/__snapshots__/Popular.test.js.snap
  src/components/PopularItems/index.jsx
  src/components/PopularItemsSection/index.jsx
Labels: enhancement

#88 Creating footer section
  .prettierignore
  .vscode/launch.json
  public/images/facebook .svg
  public/images/footerlogo.svg
  public/images/instagram (2).svg
  public/images/linkedin (2).svg
  public/images/share.svg
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.style.jsx
  src/components/Footer/__test__/Footer.test.js
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/layout/Layout.jsx
Labels: Component finished, new component

#89 shimmer effect to the dynamic content
  package-lock.json
  package.json
  src/components/ListedItems/ButtonsComp.jsx
  src/components/ListedItems/ItemsList.jsx
  src/components/ListedItems/ListedItems.jsx
  src/components/ListedItems/ListedItems.styled.jsx
  src/components/ListedItems/__test__/__snapshots__/SearchAndList.test.js.snap
  src/pages/Blogs/index.jsx
  src/pages/Products/Index.jsx
  src/pages/index.jsx
Labels: enhancement, dynamic

#91 fixing footer not to be position fixed
  src/components/Footer/Footer.style.jsx
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
Labels: fix

#93 fix scroll top
  src/components/Footer/Footer.style.jsx
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/ScrollTop/scrollTop.styled.jsx
Labels: fix

#95 Add authentication
  src/components/Sign UP/Index.jsx
  src/components/Sign UP/Signup.styled.jsx
  src/components/Sign UP/__test__/Signup.test.js
  src/components/Sign UP/__test__/__snapshots__/Signup.test.js.snap
  src/components/Signin/Signin.styled.jsx
  src/components/Signin/__test__/Signin.test.js
  src/components/Signin/__test__/__snapshots__/Signin.test.js.snap
  src/components/Signin/index.jsx
  src/pages/index.jsx
  src/schemas/index.js
Labels: enhancement, fix, firebase

#100 Change categories language depending on html lang
  src/components/Categories/index.jsx
Labels: enhancement

#98 1 navbar component
  public/images/Logo.svg
  public/images/Saudi Arabia.svg
  public/images/Turkey.svg
  public/images/arrow.svg
  public/images/flag.svg
  public/images/users.svg
  public/images/vercel.svg
  src/components/Navbar/Nav.styled.jsx
  src/components/Navbar/NavItem.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/__test__/Navbar.test.js
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/layout/Layout.jsx
Labels: bug, Component finished

#103 Shimmer loading for products categories
  src/components/CardListed/__test__/__snapshots__/CardListed.test.js.snap
  src/components/Categories/Categories.styled.jsx
  src/components/Categories/__test__/__snapshots__/Categories.test.js.snap
  src/components/Categories/index.jsx
  src/components/ListedItems/ButtonsComp.jsx
  src/components/ListedItems/ListedItems.styled.jsx
  src/components/ListedItems/__test__/__snapshots__/SearchAndList.test.js.snap
Labels: enhancement, style, feature

#105 add navbar to pages
  src/components/AddItem/Index.jsx
  src/components/AddItem/__test__/__snapshots__/AddItem.test.js.snap
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.style.jsx
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/Signin/__test__/__snapshots__/Signin.test.js.snap
  src/components/Signin/index.jsx
  src/pages/Aboutus/index.jsx
  src/pages/AddItems/index.jsx
  src/pages/Blogs/[pid].jsx
  src/pages/Blogs/index.jsx
  src/pages/Forgetpassword/index.jsx
  src/pages/Products/Index.jsx
  src/pages/Products/[pid].jsx
  src/pages/Signin/index.jsx
  src/pages/Signup/index.jsx
  src/pages/index.jsx
  src/styles/aboutus.styled.jsx
Labels: feature

#107 Add swiper to partners
  package-lock.json
  package.json
  src/assets/Image/sevenup.svg
  src/components/Partners/Partners.styled.jsx
  src/components/Partners/__test__/Partners.test.js
  src/components/Partners/__test__/__snapshots__/Partners.test.js.snap
  src/components/Partners/index.jsx
  src/pages/index.jsx
Labels: enhancement, Component finished

#111 Fix Single products page path
  src/components/AddItem/__test__/__snapshots__/AddItem.test.js.snap
  src/components/ListedItems/ItemsList.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/pages/Products/[pid].jsx
Labels: fix

#112 complete modification for authentication
  src/components/Herro/DonateButton.jsx
  src/components/Herro/__test__/Hero.test.js
  src/components/Herro/__test__/__snapshots__/Hero.test.js.snap
  src/components/ListedItems/ButtonsComp.jsx
  src/components/ListedItems/__test__/__snapshots__/SearchAndList.test.js.snap
  src/components/Navbar/Navbar.jsx
  src/components/Sign UP/Index.jsx
  src/components/Signin/__test__/__snapshots__/Signin.test.js.snap
  src/components/Signin/index.jsx
  src/pages/index.jsx
Labels: important, firebase

#119 add navbar and footer to pages
  src/components/AddItem/Index.jsx
  src/components/AddItem/__test__/__snapshots__/AddItem.test.js.snap
  src/pages/404.jsx
  src/pages/Aboutus/index.jsx
  src/pages/Blogs/[pid].jsx
  src/pages/Blogs/index.jsx
  src/pages/Forgetpassword/index.jsx
  src/pages/Products/Index.jsx
  src/pages/Products/[pid].jsx
  src/pages/Signin/index.jsx
  src/pages/Signup/index.jsx
  src/pages/_app.jsx
  src/pages/index.jsx
Labels: fix

#117 Fix Navbar dropdown menu in mobile view
  src/components/Navbar/Nav.styled.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/pages/index.jsx
Labels: fix

#121 forget password page functionality
  package-lock.json
  package.json
  src/pages/Forgetpassword/index.jsx
  src/schemas/index.js
Labels: enhancement, page completed, firebase
