Repository 202212-GIZ-YE-FEW/Tabadul, pull requests merged in 2023-03, with the labels that each got.

#15 Statistics Component
  src/assets/Image/StatisticsContainer.svg
  src/assets/Image/Vector.svg
  src/assets/Image/icon_bar_chart.svg
  src/assets/Image/icon_pie_chart.svg
  src/assets/Image/pyramid_chart.svg
  src/components/Statistics/Statistics.jsx
  src/components/Statistics/Statistics.style.jsx
  src/components/Statistics/__test__/Statistics.test.js
  src/components/Statistics/__test__/__snapshots__/Statistics.test.js.snap
  src/pages/_app.jsx
  src/styles/globals.css
Labels: Component finished

#24 22 fix overlapping of statistics section popular section
  src/components/PopularItems/__test__/__snapshots__/Popular.test.js.snap
  src/components/PopularItems/index.jsx
  src/components/Statistics/Statistics.jsx
  src/components/Statistics/Statistics.style.jsx
  src/components/Statistics/__test__/__snapshots__/Statistics.test.js.snap
  src/pages/index.jsx
  src/styles/globals.css
Labels: fix

#25 Hero Section Enhancement
  src/components/Herro/DonateButton.jsx
  src/components/Herro/IntroductionImage.jsx
  src/components/Herro/IntroductionText.jsx
  src/components/Herro/__test__/Hero.test.js
  src/components/Herro/__test__/__snapshots__/Hero.test.js.snap
  src/components/Herro/hero.style.jsx
  src/components/Herro/index.js
  src/components/Herro/index.jsx
Labels: enhancement, fix
